server:
  port: 8011
spring:
  application:
    name: underdog-service-manage-media-processor
  data:
    mongodb:
      host: 101.35.143.19
      database: underdog_video
  cloud:
    nacos:
      discovery:
        server-addr: 101.35.143.19:8848
  rabbitmq:
    host: 101.35.143.19
    virtual-host: my_vhost
    port: 5672
    username: guest
    password: guest
underdog-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: F:/develop/video/
  ffmpeg-path: D:/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe


